### PR TITLE
Add CommonMark support

### PR DESCRIPTION
**Pull request by rgomezcasas**
Add default support for CommonMark

### CODE REVIEW

**Comment by daylerees** [comment]
Can I get some info on this please?

**Comment by DotZecker** [comment]
Yes, sorry. 

I use Kurenai in my blog and I recently switched to CommonMark. It was easy implementing the `MarkdownParserInterface`, but I feel maybe more users would want be able to do this, so i thougt to add this implementation in the main project.

Kurenai uses Markdown parsers, but Markdown is not a "Standard" because it has no "[spec](http://commonmark.org/#why)". With this pull request I added CommonMark support (using the league/commonmark). I added it as a suggested package (but I think it should be the default implementation, maybe in the next major release?)

Sorry for my english! :)

Thanks!

**Comment by crynobone** [comment]
Any plan to merged this? 

> I added it as a suggested package (but I think it should be the default implementation, maybe in the next major release?)

I would personally prefer if the next major release doesn't have any default. This make it easy for developer to choose and maintain deps on their own (as well as getting the latest update without having to submit PR here).

**Comment by rgomezcasas** [comment]
I this going to be merged or should I close the pr? :shipit: :)

**Pull request closed without merging**
